export const projects = [
  {
    title: 'Old Portfolio',
    description: "My old Portfolio built with Javascript, HTML, CSS, GSAP animations. It consists of a navbar, three sections and a contact form. The site is responsive to various screen sizes. The project section displays some of my older projects.",
    image: '/images/project23.png',
    tags: ['HTML', 'CSS', 'JS'],
    source: 'https://github.com/GerPut/Portfolio',
    visit: 'https://gerhardp-old-portfolio.netlify.app/',
    id: 0,
  },
  {
    title: 'Utility Apps',
    description: "8 mini projects/apps built with HTML, CSS and Javascript. Loan Calculator, RSA random code generator, Login Form, Weather app (API), Currency exchange app (API), Shopping List (CRUD), Calculator, BTC price display and Countdown timer. ",
    image: '/images/project17.png',
    tags: ['HTML', 'CSS', 'Javascript', 'API'],
    source: 'https://github.com/GerPut/utility-apps',
    visit: 'https://gerhardp17.netlify.app/',
    id: 1,
  },
  {
    title: 'Netflix Sign In',
    description: "Page created with HTML and CSS. Many variations of the Netflix sign in page exists, with this attempt I tried to duplicate their page as close as possible.",
    image: '/images/project27.png',
    tags: ['HTML', 'CSS'],
    source: 'https://github.com/GerPut/sign-in',
    visit: 'https://gerhardp25.netlify.app/',
    id: 2,
  },
  {
    title: 'Video Background',
    description: "Project built with HTML, CSS and JS. This is a landing page with a video background that can be used as a boilerplate to expand on in the future. Extra work will be added.",
    image: '/images/project25.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/GerPut/video-landing-page',
    visit: 'https://gerhardp23.netlify.app/',
    id: 3,
  },
  {
    title: 'Games',
    description: "Front page with menu consisting of buttons to select a game the user wants to play. Old classic games built with Javascript, HTML and CSS. Games include MineSweeper, Breakout and Fruity Slots",
    image: '/images/project32.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/GerPut/games',
    visit: 'https://gerhardp27.netlify.app/',
    id: 4,
  },
  {
    title: 'Odds App',
    description: "This app was built with HTML, CSS and Javascript. I created for myself to check for possible discrepancies between betting lines of UFC events. I hard coded my own stats and formulas.",
    image: '/images/project29.png',
    tags: ['Javascrip', 'HTML', 'CSS'],
    source: 'https://github.com/GerPut/stats-app',
    visit: 'https://gerhardp26.netlify.app/',
    id: 5,
  },
  {
    title: 'Password Strength',
    description: "React app to check a user's password strength according to certain criteria. The Criteria is made up from Regex patterns that check for password length, uppercase letters, symbols and numbers",
    image: '/images/project34.jpg',
    tags: ['HTML', 'CSS', 'React'],
    source: 'https://github.com/GerPut/password-strength',
    visit: 'https://gerhardp15.netlify.app/',
    id: 6,
  },
  {
    title: 'Service Page',
    description: "Service page site for a Poker training program. The project is responsive to all screen sizes. The project was built with HTML, CSS grid along with some basic ScrollMagic animations.",
    image: '/images/project20.png',
    tags: ['HTML', 'CSS', 'CSS-Grid', 'ScrollMagic'],
    source: 'https://github.com/GerPut/service-page',
    visit: 'https://gerhardp20.netlify.app/',
    id: 7,
  },
  {
    title: 'Car List',
    description: "Basic app built with React hooks and bootstrap styles. Client can add and remove items/data to and from a list that gets stored in localStorage.",
    image: '/images/project18.png',
    tags: ['React', 'Bootstrap'],
    source: 'https://github.com/GerPut/car-list',
    visit: 'https://gerhardp18.netlify.app/',
    id: 8,
  },
  {
    title: 'Shopping Cart',
    description: "This is a small and basic project built with React. The shoppping cart is styled with Bootsrap 5 and some extra custom CSS classes. User can add and remove items to and from cart and a total amount gets calculated.",
    image: '/images/project13a.png',
    tags: ['React', 'Bootstrap'],
    source: 'https://github.com/GerPut/cart',
    visit: 'https://gerhardp13.netlify.app/',
    id: 9,
  },
  {
    title: 'Image Search',
    description: "Project built with React and Tailwindcss. User can search for images using the search bar. Images are provided with an API that fetches the images and some data that gets displayed under each image. If there aren't any images to display a custom message will show on screen.",
    image: '/images/project21.png',
    tags: ['React', 'Tailwindcss'],
    source: 'https://github.com/GerPut/image-search',
    visit: 'https://gerhard21.netlify.app',
    id: 10,
  },
  {
    title: 'Movie Site',
    description: "A project built with WordPress + Elementor website builder. The site is for demo purposes and contains different sections based on a StarWars movie. With the help of tutorials I have gained more experience in working with Elementor.",
    image: '/images/project30.png',
    tags: ['WordPress', 'Elementor'],
    source: 'https://gp-demo-1.live/',
    visit: 'https://gp-demo-1.live/',
    id: 11,
  },
  {
    title: 'Client Site',
    description: "This site was built using Bootstrap. I added custom animate on scroll animations and also custom Whatsapp and Telephone links. It is a one page site as requested by client. The theme of the website is for a Woodwork niche.",
    image: '/images/project22.png',
    tags: ['Bootstrap', 'AOS', 'HTML', 'CSS'],
    source: 'https://www.groovhoutmeubels.co.za/',
    visit: 'https://www.groovhoutmeubels.co.za/',
    id: 12,
  },
  {
    title: 'Client Site-2',
    description: "Bootstrap site build for an accountant. The site has a video background and some animate on scroll animations. The site is fully responsive to all screen sizes.",
    image: '/images/project37.png',
    tags: ['Bootstrap', 'AOS', 'HTML', 'CSS'],
    source: 'https://www.ssprofessionalaccounting.co.za/',
    visit: 'https://www.ssprofessionalaccounting.co.za/',
    id: 13,
  },
  {
    title: 'Client Site-3',
    description: "Website built with WordPress and Elementor for a MTB niche. Several plugins used for bookings and payment integration. Custom CSS implemented for certain styles of elements.",
    image: '/images/project39.png',
    tags: ['Javascript', 'Wordpress', 'HTML', 'CSS', 'Elementor'],
    source: 'https://schoolofcycling.co.za',
    visit: 'https://schoolofcycling.co.za/',
    id: 14,
  },
  {
    title: 'Course Site',
    description: "This four page website was built according to intructions given in a UCT web design course. The main languages used to create everything from scratch were HTML, CSS and Javascript.",
    image: '/images/project38.png',
    tags: ['Javascript', 'AOS', 'HTML', 'CSS'],
    source: 'https://github.com/GerPut/uct-project',
    visit: 'http://trekrun.co.za/',
    id: 15,
  },
  {
    title: 'Modern Site',
    description: "Modern website built with React and Css from a Figma design following the BEM methodology. The site has Animate on Scroll animations and is responsive to all screen sizes.",
    image: '/images/project31.png',
    tags: ['React', 'Animate on Scroll', 'CSS'],
    source: 'https://github.com/GerPut/react-modern-site',
    visit: 'https://react-modern-site.vercel.app/',
    id: 16,
  },
  {
    title: 'Card Validation',
    description: "Project created with Javascript, HTML and CSS to validate credit card numbers. The functionality of the app uses the Luhn algorithm to calculate validity of the card number. If the card number and country is valid the user can save the details to local storage.",
    image: '/images/project33.jpg',
    tags: ['Javascript', 'Toastify', 'CSS', 'HTML'],
    source: 'https://github.com/GerPut/card-check',
    visit: 'https://gerhardp30.netlify.app/',
    id: 17,
  },
  {
    title: 'Chrome Extension',
    description: "Chrome extension built with Javascript, HTML and CSS that can be installed to save URL's in a list. The list gets saved to local storage and can be cleared by double clicking on Delete button. ",
    image: '/images/project36.png',
    tags: ['Javascript', 'Toastify', 'CSS', 'HTML'],
    source: 'https://github.com/GerPut/chrome-extension',
    visit: 'https://subtle-shortbread-79e781.netlify.app/',
    id: 18,
  },
  {
    title: 'Shopify',
    description: "Theme development work with O.S1.0 stores (Themekit). Also Work with O.S2.0 stores (Shopify CLI). Fixing bugs in code and resolving issues with 3rd party apps. Mostly worked with Javascript, CSS, HTML, Liquid and JSON.",
    image: '/images/project40.png',
    tags: ['Javascript', 'CSS', 'HTML', 'JSON', 'Liquid'],
    source: '',
    visit: '',
    id: 19,
  }
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];