export const projects = [
  {
    title: 'Fruity Slots',
    description: "Game Project. A Fruit Slots model was built with HTML, CSS and JS. The aim of the game is to produce random pictures that create a spinning action and stops at set times.",
    image: '/images/fruity1a.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/GerPut/fruity_slots',
    visit: 'https://gerhardp4.netlify.app/',
    id: 0,
  },
  {
    title: 'Store Page',
    description: "A single page e-commerce store created with Bootsrap, CSS and JS. The page includes animations on scroll a Countdown timer and a current Bitcoin price displayer (Use of an API).",
    image: '/images/project16.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/GerPut/store',
    visit: 'https://gerhardp16.netlify.app/',
    id: 1,
  },
  {
    title: 'Menu & Modal',
    description: "Project built with HTML, CSS and JS that consists of a modal and side-nav menu. Client side form validation is a common occurence. The form and menu are responsive to all screen sizes.",
    image: '/images/project12.png',
    tags: ['React', 'WebRTC'],
    source: 'https://github.com/GerPut/modal-form',
    visit: 'https://gerhardp12.netlify.app/',
    id: 2,
  },
  {
    title: 'Message Clock & Score',
    description: "Message Clock and Score Keeper app with a neumorphic design built with HTML, SASS and JS. This app allows you to keep score of a game and provides your current time with a greeting depending on what time of the day it is.",
    image: '/images/project7a.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/scorekeeper',
    visit: 'https://gerhardp7.netlify.app/',
    id: 3,
  },
  {
    title: 'Burger Bros',
    description: "Burger Restaurant page built with HTML, CSS and JS. The focus of the project was to expand on CSS skills. Various CSS features were used in the development of this page for example moving/zooming background, button animations, slide-in side navbar.",
    image: '/images/project8.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/burger-site',
    visit: 'https://gerhardp8.netlify.app/',
    id: 4,
  },
  {
    title: 'Newsletter',
    description: "A newsletter designed and built using HTML and CSS and a basic Gsap animation. I tried to follow BEM principles in creating the newsletter and made the page responsive to all screen sizes using media queries. The project includes a search bar where an user can search for news (Use of an API).",
    image: '/images/project9d.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/newsletter',
    visit: 'https://gerhardp9.netlify.app/',
    id: 5,
  },
  {
    title: 'Boots',
    description: "Example of a Boots Sale Page built with HTML, CSS and Gsap animations. The page has an overlay animation with appearing elements and a distortion effect when hovering over the main image.",
    image: '/images/project10.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/boots',
    visit: 'https://gerhardp10.netlify.app/',
    id: 6,
  },
  {
    title: 'Accountant',
    description: "Project built for a client. I've taken a mobile first approach with this project.The project is responsive to all screen sizes. The project was built with HTML, CSS grid along with some basic ScrollMagic animations.",
    image: '/images/project11.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/accounting',
    visit: 'https://gerhardp11.netlify.app/',
    id: 7,
  },
  {
    title: 'Password Strength',
    description: "Basic React project with one component and CSS styling to check the strength of a user's password.",
    image: '/images/project15.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/password-strength',
    visit: 'https://gerhardp15.netlify.app/',
    id: 8,
  },
  {
    title: 'Staff Management',
    description: "This is a basic React app that can be used to assign staff duties for the day. It consists of a form that uses the user input to display a list of names and duties. The user can add and delete names to and from the list.",
    image: '/images/project14.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/staff-management',
    visit: 'https://gerhardp14.netlify.app/',
    id: 9,
  },
  {
    title: 'Shopping Cart',
    description: "This is a small and basic project built with React. The shoppping cart is styled with Bootsrap 5 and some extra custom CSS classes. User can add and remove items to and from cart and a total amount gets calculated.",
    image: '/images/project13a.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/GerPut/cart',
    visit: 'https://gerhardp13.netlify.app/',
    id: 10,
  },
  {
    title: 'Utility Apps',
    description: "This project contains 5 other mini projects built with HTML, CSS and Javascript. These mini projects include a Loan Calculator, RSA random code generator, Login Form, Weather app (Use of an API) and a Currency exchange app. ",
    image: '/images/project17.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];